### PR TITLE
android-tools-adb: update to 9.0 based on FreeBSD patches

### PR DESCRIPTION
**Pull request by jbeich**
Only tested TCP backend on NetBSD.

### CODE REVIEW

**Comment by krytarowski** [comment]
You seem to note patches, but they are not included. Are they forgotten?

For pkgsrc-wip, we recommend to get contributors to commit directly: http://pkgsrc.org/wip/

BTW. Are you interested in Android Studio? There is a port of HAXM now for emulator.. we need someone to package it. It's in Java and it's a show stopper for me.

**Comment by jbeich** [comment]
> You seem to note patches, but they are not included. Are they forgotten?

Patches are treated as regular distfiles aka vendor patches. Handling code churn on updates is left to FreeBSD Ports.

> For pkgsrc-wip, we recommend to get contributors to commit directly: http://pkgsrc.org/wip/

I don't use NetBSD or PkgSrc. It was mostly one-off effort and to facilitate porting android-tools-fastboot.

> Are you interested in Android Studio?

Not yet. Even on FreeBSD.

**Comment by jbeich** [comment]
@sthen, can you check build on OpenBSD? Alternatively, try porting the patch vendoring approach into OpenBSD Ports. If more patches are required you can apply those on top via `patches/` subdirectory, and I can pick up them later (to keep sanity).

Here's how simple build works:
1. Extract upstream sources to WRKSRC
2. Download FreeBSD patches and (sub)Makefile
3. Apply all patches
4. make MDNSEXT=_unsupported -C WRKSRC/adb -f /path/to/Makefile

**Comment by 0-wiz-0** [comment]
This read-only copy of the main repository does not accept pull requests.

Please read http://pkgsrc.org/wip/users/ on how to get access to the main repository. Thanks!

**Pull request closed without merging**
